version: "3.9"

services:
  # webのフロントエンドのコンテナ
  frontend-web:
    image: "node"
    container_name: chefs-frontend-web
    volumes:
        - "./:/var/www/html"
    working_dir: "/var/www/html"
    ports:
        - "23000:3000"
    command: bash -c "npm ci && npm run dev"
